using System.Diagnostics;
using System.Net.Sockets;
using System.Text;
using System.Text.Json;
using Madre.Kernel;
using Microsoft.Data.Sqlite;

internal static partial class Program
{
    private static async Task RunQualificationStressAsync(VerificationOptions options)
    {
        int n = Math.Min(ScaleWorkCount(options.Scale), 2000);
        await ConcurrencyAndQueueStressAsync(n); await CapabilityScaleStressAsync(Math.Min(1000, n));
        foreach (int seed in new[] { 0x00C0FFEE, 0x05EED123, 0x0BADC0DE }) await SeededPhysicalModelAsync(seed, Math.Max(1000, n));
    }

    private static async Task RunStressVerificationAsync(VerificationOptions options)
    {
        int n = ScaleWorkCount(options.Scale); await ConcurrencyAndQueueStressAsync(n); await CapabilityScaleStressAsync(Math.Min(1000, n));
        foreach (int seed in new[] { 0x00C0FFEE, 0x05EED123, 0x0BADC0DE, options.Seed }.Distinct()) await SeededPhysicalModelAsync(seed, Math.Max(2000, n));
        await RawIpcFuzzStressAsync(options.Seed, Math.Max(500, n)); await RestartChaosStressAsync(options.Seed, Math.Max(100, n / 2));
    }

    private static async Task ConcurrencyAndQueueStressAsync(int requested)
    {
        foreach (int slots in new[] { 1, 2, 4, 8, 32 })
        {
            using var temp = new TempDir($"verify-slots-{slots}"); var binding = new ControlledBinding($"controlled/slots-{slots}", "1") { ExecuteHandler = async (r, ct) => { int i = int.Parse(r.PreparedInput.AsSpan(2)); if (i % 19 == 0) return BindingExecutionResult.Fail(PhysicalFailureKind.IoFailure); if (i % 23 == 0) return BindingExecutionResult.Unknown(); if (i % 7 == 0) await Task.Delay(1, ct); return BindingExecutionResult.Success(r.PreparedInput); } }; InferenceCapability cap = Capability($"slots-{slots}", binding.BindingId, "1", InferenceEffort.High, ExecutionBoundary.LocalOnly, 1);
            await using var engine = new KernelEngine(new WorkStore(Path.Combine(temp.Path, "load.db")), [cap], [binding], slots); await engine.InitializeAsync(); await engine.RefreshCapabilityStatesAsync(); engine.Start(); int count = Math.Max(slots * 10, requested); var ids = new List<string>(count); for (int i = 0; i < count; i++) ids.Add(await engine.SubmitAsync(Req($"w:{i}", InferenceEffort.Low, (WorkUrgency)(i % 3), ExecutionBoundary.LocalOnly))); await WaitAllTerminalAsync(engine, ids, Math.Max(30000, count * 20)); IReadOnlyList<WorkInspection> works = await InspectAllAsync(engine, ids); AssertGlobalPhysicalInvariants(works, binding.MaxActive, slots); Check(works.All(w => w.Attempts.Count == 1) && binding.Active == 0, $"attempt/slot leak at maxConcurrent={slots}");
        }

        using var qtemp = new TempDir("verify-queue-10k"); DateTimeOffset now = new(2026, 9, 28, 3, 0, 0, TimeSpan.Zero); var clock = new ManualKernelClock(now); var qb = new ControlledBinding("controlled/queue", "1"); InferenceCapability qc = Capability("queue", qb.BindingId, "1", InferenceEffort.High, ExecutionBoundary.LocalOnly, 1); await using var qe = new KernelEngine(new WorkStore(Path.Combine(qtemp.Path, "queue.db")), [qc], [qb], 32, clock); await qe.InitializeAsync(); await qe.RefreshCapabilityStatesAsync(); qe.Start(); int queueCount = Math.Max(10000, requested); var future = new List<string>(); DateTimeOffset shared = now.AddMinutes(1); for (int i = 0; i < queueCount; i++) future.Add(await qe.SubmitAsync(new($"q{i}", InferenceEffort.Low, (WorkUrgency)(i % 3), shared, shared.AddHours(1), ExecutionBoundary.LocalOnly))); Check(qb.ExecutionCount == 0, "future queue consumed slot"); clock.Advance(TimeSpan.FromMinutes(1)); await WaitAllTerminalAsync(qe, future, Math.Max(60000, queueCount * 10)); Check((await InspectAllAsync(qe, future)).All(w => w.State == WorkState.Succeeded), "eligible queue stranded Work");
    }

    private static async Task CapabilityScaleStressAsync(int requested)
    {
        using var temp = new TempDir("verify-cap-scale");
        foreach (int count in new[] { 0, 1, Math.Min(100, requested), Math.Min(1000, requested) }.Distinct())
        {
            var b = new ControlledBinding($"controlled/caps-{count}", "1", CapabilityAvailability.Available); InferenceCapability[] caps = Enumerable.Range(0, count).Select(i => Capability($"cap-{i}", b.BindingId, "1", InferenceEffort.Low, ExecutionBoundary.LocalOnly, i)).ToArray(); await using var e = new KernelEngine(new WorkStore(Path.Combine(temp.Path, $"{count}.db")), caps, count == 0 ? [] : [b], 4); Stopwatch startup = Stopwatch.StartNew(); await e.InitializeAsync(); e.Start(); startup.Stop(); Check(startup.Elapsed < TimeSpan.FromSeconds(5), "probe blocked startup"); if (count > 0) { IReadOnlyList<CapabilitySnapshot> s = await e.RefreshCapabilityStatesAsync(); Check(s.Count == count && s.All(x => x.State.Availability == CapabilityAvailability.Available), "capability scale observation mismatch"); }
        }
        var unavailable = new ControlledBinding("controlled/unavailable", "1", CapabilityAvailability.Unavailable); InferenceCapability cap = Capability("unavailable", unavailable.BindingId, "1", InferenceEffort.Low, ExecutionBoundary.LocalOnly, 1); await using var engine = new KernelEngine(new WorkStore(Path.Combine(temp.Path, "demand.db")), [cap], [unavailable], 4, timing: new KernelTimingOptions(TimeSpan.FromMilliseconds(50), TimeSpan.FromMilliseconds(25))); await engine.InitializeAsync(); await engine.RefreshCapabilityStatesAsync(); engine.Start(); int baseline = unavailable.ProbeCount; var ids = new List<string>(); for (int i = 0; i < 200; i++) ids.Add(await engine.SubmitAsync(Req($"wait-{i}", InferenceEffort.Low, WorkUrgency.Normal, ExecutionBoundary.LocalOnly))); await Task.Delay(150); Check(unavailable.ProbeCount - baseline < 20 && unavailable.ExecutionCount == 0, "unavailable shared demand probe/slot amplification"); foreach (string id in ids) _ = await engine.CancelAsync(id); int after = unavailable.ProbeCount; await Task.Delay(100); Check(unavailable.ProbeCount <= after + 1, "idle unavailable capability continuously reprobed");
    }

    private static async Task SeededPhysicalModelAsync(int seed, int operations)
    {
        Console.WriteLine($"MODEL seed={seed} operations={operations}"); using var temp = new TempDir("verify-model"); DateTimeOffset start = new(2026, 9, 28, 5, 0, 0, TimeSpan.Zero); var clock = new ManualKernelClock(start); var binding = new ControlledBinding("controlled/model", "1") { ExecuteHandler = (r, _) => Task.FromResult(r.PreparedInput.Contains("fail", StringComparison.Ordinal) ? BindingExecutionResult.Fail(PhysicalFailureKind.IoFailure) : BindingExecutionResult.Success(r.PreparedInput)) }; InferenceCapability cap = Capability("model", binding.BindingId, "1", InferenceEffort.High, ExecutionBoundary.LocalOnly, 1); string db = Path.Combine(temp.Path, "model.db"); KernelEngine engine = await StartModel(db, cap, binding, clock); var random = new Random(seed); var ids = new List<string>(); var states = new Dictionary<string, WorkState>(); var history = new Queue<string>();
        try { for (int step = 0; step < operations; step++) { int action = random.Next(8); string log; if (action < 3) { DateTimeOffset? eligible = random.Next(5) == 0 ? clock.UtcNow.AddSeconds(random.Next(1, 20)) : null; string id = await engine.SubmitAsync(new($"m{step}-{(random.Next(10)==0?"fail":"ok")}", (InferenceEffort)random.Next(3), (WorkUrgency)random.Next(3), eligible, eligible?.AddSeconds(30), ExecutionBoundary.LocalOnly)); ids.Add(id); states[id] = WorkState.Queued; log = $"submit {id}"; } else if (action == 3) { clock.Advance(TimeSpan.FromSeconds(random.Next(1, 60))); log = "advance"; } else if (action == 4 && ids.Count > 0) { string id = ids[random.Next(ids.Count)]; _ = await engine.CancelAsync(id); log = $"cancel {id}"; } else if (action == 5) { binding.Availability = (CapabilityAvailability)random.Next(3); _ = await engine.RefreshCapabilityStatesAsync(); log = $"cap {binding.Availability}"; } else if (action == 6 && ids.Count > 0) { string id = ids[random.Next(ids.Count)]; WorkInspection? w = await engine.InspectAsync(id); if (w is not null && IsTerminal(w.State)) _ = await engine.ReleaseAsync(id); log = $"release {id}"; } else { await engine.DisposeAsync(); engine = await StartModel(db, cap, binding, clock); log = "restart"; } history.Enqueue($"{step} {log}"); while (history.Count > 100) history.Dequeue(); if (ids.Count > 0) { string id = ids[random.Next(ids.Count)]; WorkInspection w = (await engine.InspectAsync(id))!; if (states.TryGetValue(id, out WorkState old) && IsTerminal(old)) Check(w.State == old, $"terminal state resurrected {old}->{w.State}"); states[id] = w.State; AssertGlobalPhysicalInvariants([w], binding.MaxActive, 4); } } binding.Availability = CapabilityAvailability.Available; _ = await engine.RefreshCapabilityStatesAsync(); clock.Advance(TimeSpan.FromDays(2)); await WaitAllTerminalAsync(engine, ids, Math.Max(30000, ids.Count * 20)); AssertGlobalPhysicalInvariants(await InspectAllAsync(engine, ids), binding.MaxActive, 4); }
        catch { Console.Error.WriteLine($"MODEL FAILURE seed={seed}"); foreach (string h in history) Console.Error.WriteLine(h); throw; } finally { await engine.DisposeAsync(); }
    }

    private static async Task<KernelEngine> StartModel(string db, InferenceCapability cap, ControlledBinding binding, IKernelClock clock)
    { var e = new KernelEngine(new WorkStore(db), [cap], [binding], 4, clock, new KernelTimingOptions(TimeSpan.FromMilliseconds(100), TimeSpan.FromSeconds(1))); await e.InitializeAsync(); await e.RefreshCapabilityStatesAsync(); e.Start(); return e; }

    private static async Task RawIpcFuzzStressAsync(int seed, int iterations)
    {
        Console.WriteLine($"FUZZ seed={seed} iterations={iterations}"); using var temp = new TempDir("verify-fuzz"); TestEnv env = MakeEnv(temp.Path, true, true); File.WriteAllText(env.SlowState, "available"); File.WriteAllText(env.FastState, "unavailable"); await using var kernel = await KernelProcess.StartAsync(env.Config, env.Database, env.Socket, 2); var client = new IpcClient(env.Socket); await WaitCapabilityAsync(client, Slow, CapabilityAvailability.Available); var random = new Random(seed);
        for (int i = 0; i < iterations; i++) { int kind = random.Next(6); if (kind == 0) _ = await SendRawFrameAsync(env.Socket, random.Next(2)==0?0:-1, ReadOnlyMemory<byte>.Empty); else if (kind == 1) { byte[] b = new byte[random.Next(1,128)]; random.NextBytes(b); _ = await SendRawFrameAsync(env.Socket, b.Length, b); } else if (kind == 2) _ = await RawIpcAsync(env.Socket, $"{{\"version\":{KernelProtocol.Version},\"requestId\":\"{i}😀\",\"operation\":\"NoSuch\",\"payload\":null}}"); else if (kind == 3) _ = await RawIpcAsync(env.Socket, "{"); else { int n = kind == 4 ? KernelProtocol.MaxPayloadBytes : KernelProtocol.MaxPayloadBytes + 1; _ = await RawIpcAsync(env.Socket, JsonSerializer.Serialize(new { version=KernelProtocol.Version, requestId=$"p{i}", operation="Submit", payload=new { preparedInput=new string('x',n), requestedEffort="Low", urgency="Normal", executionBoundary="LocalOnly" } })); } if (i % 50 == 0) Check((await client.CallAsync<Health>("Health", null)).Status == "ok", $"fuzz damaged host seed={seed} i={i}"); }
        await AssertCleanIpcWorkAsync(client, "fuzz-final");
    }

    private static async Task RestartChaosStressAsync(int seed, int work)
    {
        using var temp = new TempDir("verify-chaos"); TestEnv env = MakeEnv(temp.Path, true, true); File.WriteAllText(env.SlowState, "available"); File.WriteAllText(env.FastState, "unavailable"); await using var kernel = await KernelProcess.StartAsync(env.Config, env.Database, env.Socket, 4); var client = new IpcClient(env.Socket); await WaitCapabilityAsync(client, Slow, CapabilityAvailability.Available); var random = new Random(seed); var ids = new List<string>(); var markers = new Dictionary<string,string>();
        for (int i=0;i<work;i++) { string input; if (i%10==0) { string m=Path.Combine(temp.Path,$"m{i}.txt"); markers[$"pending-{i}"]=m; input=$"SLOW:{random.Next(5,100)}|{m}"; } else input=i%17==0?"FAIL":$"SLOW:{random.Next(5,100)}"; string id=await SubmitAsync(client,Req(input,InferenceEffort.Standard,(WorkUrgency)(i%3),ExecutionBoundary.LocalOnly)); ids.Add(id); if(i%10==0){ string m=markers[$"pending-{i}"]; markers.Remove($"pending-{i}"); markers[id]=m;} if(i%31==0&&i>0){await kernel.RestartAsync(); client=new IpcClient(env.Socket);} if(i%13==0&&ids.Count>1){try{_=await client.CallAsync<CancelReply>("Cancel",new WorkIdArg(ids[random.Next(ids.Count)]));}catch(InvalidOperationException){}} }
        for(int i=0;i<3;i++){await Task.Delay(20);await kernel.RestartAsync();client=new IpcClient(env.Socket);} File.WriteAllText(env.SlowState,"available");_=await client.CallAsync<List<CapabilitySnapshot>>("RefreshCapabilities",null); foreach(string id in ids){WorkInspection w=await WaitIpcTerminalAsync(client,id,30000);Check(w.State!=WorkState.Running&&w.Attempts.All(a=>a.Outcome!=PhysicalAttemptOutcome.Running),"restart chaos left Running truth");} foreach(string m in markers.Values.Where(File.Exists)) Check(File.ReadAllLines(m).Length==1,"restart chaos duplicated marker side effect"); await AssertCleanIpcWorkAsync(client,"chaos-final");
    }

    private static async Task RunSoakVerificationAsync(VerificationOptions options)
    {
        Console.WriteLine($"SOAK seed={options.Seed} duration={options.SoakDuration}"); using var temp=new TempDir("verify-soak");TestEnv env=MakeEnv(temp.Path,true,true);File.WriteAllText(env.SlowState,"available");File.WriteAllText(env.FastState,"unavailable");await using var kernel=await KernelProcess.StartAsync(env.Config,env.Database,env.Socket,4);var client=new IpcClient(env.Socket);await WaitCapabilityAsync(client,Slow,CapabilityAvailability.Available);var random=new Random(options.Seed);var ids=new List<string>();Stopwatch duration=Stopwatch.StartNew();Stopwatch restart=Stopwatch.StartNew();int submitted=0,restarts=0;
        while(duration.Elapsed<options.SoakDuration){int a=random.Next(8);if(a<5){string input=a==0?"FAIL":a==1?"SLOW:60":a==2?new string('x',1024):$"soak-{submitted}";try{ids.Add(await SubmitAsync(client,Req(input,InferenceEffort.Standard,(WorkUrgency)random.Next(3),ExecutionBoundary.LocalOnly)));submitted++;}catch(Exception ex)when(ex is IOException or SocketException){throw new InvalidOperationException("unexpected soak IPC fatality",ex);}}else if(a==5)Check((await client.CallAsync<Health>("Health",null)).Status=="ok","soak health failed");else if(a==6&&ids.Count>0){try{_=await client.CallAsync<CancelReply>("Cancel",new WorkIdArg(ids[random.Next(ids.Count)]));}catch(InvalidOperationException){}}else{File.WriteAllText(env.SlowState,"unavailable");_=await client.CallAsync<List<CapabilitySnapshot>>("RefreshCapabilities",null);File.WriteAllText(env.SlowState,"available");_=await client.CallAsync<List<CapabilitySnapshot>>("RefreshCapabilities",null);}if(restart.Elapsed>TimeSpan.FromSeconds(5)){await kernel.RestartAsync();client=new IpcClient(env.Socket);restart.Restart();restarts++;}await Task.Delay(5);}await kernel.RestartAsync();client=new IpcClient(env.Socket);restarts++;int completed=0;foreach(string id in ids){WorkInspection w=await WaitIpcTerminalAsync(client,id,30000);Check(w.State!=WorkState.Running&&w.Attempts.All(x=>x.Outcome!=PhysicalAttemptOutcome.Running),"soak left Running truth");if(IsTerminal(w.State))completed++;}await AssertCleanIpcWorkAsync(client,"soak-final");using Process p=Process.GetCurrentProcess();Console.WriteLine($"SOAK diagnostics submitted={submitted} completed={completed} restarts={restarts} verifierWorkingSetBytes={p.WorkingSet64} verifierHandles={p.HandleCount} dbBytes={new FileInfo(env.Database).Length}");
    }
}
