"""Strongly typed public building blocks for independent MADRE Modules."""

from madre_sdk.algebra import Autonomy, Integrity, Privacy, Risk, Sensitivity
from madre_sdk.codecs import ModuleDefinitionJsonCodec, ModuleDirectoryJsonCodec
from madre_sdk.definitions import (
    AgentDefinition,
    DisplayName,
    EffectProfile,
    ModuleDefinition,
    ModuleDirectoryEntry,
    OperationCall,
    OperationDefinition,
    Purpose,
    Repeatability,
    SkillDefinition,
    WorkflowDefinition,
)
from madre_sdk.execution import (
    ComputationContract,
    ExecutionLocation,
    LatencyClass,
    LatencyPreference,
    LatencyRequirement,
    LocationPreference,
    LocationRequirement,
    PhysicalPreference,
    PhysicalProperties,
    PhysicalRequirement,
    PhysicalResult,
    PhysicalRetryPolicy,
    Priority,
    WorkRequest,
    WorkTiming,
)
from madre_sdk.identity import (
    AgentId,
    ComputationId,
    EffectProfileId,
    MaterialId,
    MaterialTypeId,
    ModuleId,
    OperationId,
    SkillId,
    SurfaceId,
    WorkflowId,
)
from madre_sdk.material import Material, MaterialSet, MaterialType
from madre_sdk.ports import ExecutionService, ModuleDirectory, OperationImplementation
from madre_sdk.surfaces import (
    InputSurface,
    InputSurfaces,
    OutputSurface,
    OutputSurfaces,
    ResponsibilitySurface,
    ResponsibilitySurfaces,
)
from madre_sdk.work_codecs import (
    MaterialSetJsonCodec,
    PhysicalResultJsonCodec,
    WorkRequestJsonCodec,
)

__all__ = [
    "AgentDefinition",
    "AgentId",
    "Autonomy",
    "ComputationContract",
    "ComputationId",
    "DisplayName",
    "EffectProfile",
    "EffectProfileId",
    "ExecutionLocation",
    "ExecutionService",
    "InputSurface",
    "InputSurfaces",
    "Integrity",
    "LatencyClass",
    "LatencyPreference",
    "LatencyRequirement",
    "LocationPreference",
    "LocationRequirement",
    "Material",
    "MaterialId",
    "MaterialSet",
    "MaterialSetJsonCodec",
    "MaterialType",
    "MaterialTypeId",
    "ModuleDefinition",
    "ModuleDefinitionJsonCodec",
    "ModuleDirectory",
    "ModuleDirectoryEntry",
    "ModuleDirectoryJsonCodec",
    "ModuleId",
    "OperationCall",
    "OperationDefinition",
    "OperationId",
    "OperationImplementation",
    "OutputSurface",
    "OutputSurfaces",
    "PhysicalPreference",
    "PhysicalProperties",
    "PhysicalRequirement",
    "PhysicalResult",
    "PhysicalResultJsonCodec",
    "PhysicalRetryPolicy",
    "Priority",
    "Privacy",
    "Purpose",
    "Repeatability",
    "ResponsibilitySurface",
    "ResponsibilitySurfaces",
    "Risk",
    "Sensitivity",
    "SkillDefinition",
    "SkillId",
    "SurfaceId",
    "WorkflowDefinition",
    "WorkflowId",
    "WorkRequest",
    "WorkRequestJsonCodec",
    "WorkTiming",
]
