"""Public MADRE SDK boundary for Modules and agentic integrations."""

from pydantic import JsonValue

from madre.contracts import (
    CorrelationEntry,
    ExecutionConstraints,
    FallbackPolicy,
    InferenceHardRequirements,
    InferencePreferences,
    InferenceRequirement,
    MaterialHandle,
    TransientInferenceRequest,
    TransientInferenceResult,
    TransientMaterial,
    WorkRecord,
    WorkSubmission,
)
from madre.interfaces import (
    AgentBrokering,
    AgentEndpointRegistration,
    Discovery,
    DurableWorkSubmission,
    MaterialResolutionRegistration,
    ModuleRegistration,
    OperationBrokering,
    OperationEndpointRegistration,
    TransientInference,
    WorkInspection,
    WorkResultAccess,
)
from madre.security import (
    MaterialSecurityValues,
    OperationSecurityValues,
    OrdinarySecurityLevel,
    SecurityContext,
    SecurityLevel,
    SecurityObject,
)
from madre_sdk.material import Artifact, ContextBundle, MaterialRepository, content_digest
from madre_sdk.security import actor_security, operation_security, security_context
from madre_sdk.semantic import (
    Agent,
    AgentBehavior,
    Module,
    Operation,
    OperationBehavior,
    Skill,
    Workflow,
    WorkPlan,
)
from madre_sdk.services import (
    AgentBrokerClient,
    CoreDelegate,
    CoreSelection,
    DiscoveryClient,
    InferenceClient,
    OperationBrokerClient,
    WorkClient,
    WorkResults,
)

__all__ = [
    "Agent",
    "AgentBehavior",
    "AgentBrokerClient",
    "AgentBrokering",
    "AgentEndpointRegistration",
    "Artifact",
    "ContextBundle",
    "CoreDelegate",
    "CoreSelection",
    "CorrelationEntry",
    "Discovery",
    "DiscoveryClient",
    "DurableWorkSubmission",
    "ExecutionConstraints",
    "FallbackPolicy",
    "InferenceClient",
    "InferenceHardRequirements",
    "InferencePreferences",
    "InferenceRequirement",
    "JsonValue",
    "MaterialHandle",
    "MaterialRepository",
    "MaterialResolutionRegistration",
    "MaterialSecurityValues",
    "Module",
    "ModuleRegistration",
    "Operation",
    "OperationBehavior",
    "OperationBrokering",
    "OperationEndpointRegistration",
    "OperationBrokerClient",
    "OperationSecurityValues",
    "OrdinarySecurityLevel",
    "SecurityContext",
    "SecurityLevel",
    "SecurityObject",
    "Skill",
    "TransientInference",
    "TransientInferenceRequest",
    "TransientInferenceResult",
    "TransientMaterial",
    "Workflow",
    "WorkClient",
    "WorkInspection",
    "WorkPlan",
    "WorkRecord",
    "WorkResultAccess",
    "WorkResults",
    "WorkSubmission",
    "actor_security",
    "content_digest",
    "operation_security",
    "security_context",
]
